[features]
default = ["embassy-rp", "spi"]
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-run --chip STM32F103C8"
# runner = "probe-run --chip STM32G431CBUx"
runner = "probe-run --chip rp2040"
rustflags = [
  "-C", "link-arg=-Tlink.x",
# --- ADD following new flag ---
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"
